### ISSUE TITLE
php-zip extension is no where to be found :(

### ISSUE THREAD

**Issue by kotoxie** [krissss/yourls-download-plugin#2]
php-zip extension is no where to be found :(

**Comment by krissss** [comment]
Install from [official website](https://www.php.net/manual/en/book.zip.php)

**Comment by wohfab** [comment]
Well, the installation docs don't say anything about how to actually install it.

Can this be bundled into the plugin?

**Comment by krissss** [comment]
No, php extension should install by your system.
You can search in google, [ex: how to install php-zip](https://www.google.com/search?q=how+to+install+php-zip)
